resilience4j:
  circuitbreaker:
    instances:
      portfolioService:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000
        sliding-window-size: 10
        minimum-number-of-calls: 5

